baseURL = "https://yellowdus.cc"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Yellow Dusk"
theme = "hermit"

Paginate = 10

[taxonomies]
    tags = "tags"

[params]
    dateform             = "Jan 2, 2006"
    dateformshort        = "Jan 2"
    dateformNum          = "2006-01-02"
    dateformNumTime      = "2006-01-02 15:04 -0700"
    homepage             = "main"
    description          = "Yellow Dusk"
    themeColor           = "#494f5c"
    homeSubtitle         = "When the sun reaches the Abyss of Anxiety, this is called Yellow Dusk."
    justifyContent       = true
    relatedPosts         = false
    code_copy_button     = false
    footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]


  [[menu.main]]
    name = "blog"
    url = "blog/"
    weight = 10

  [[menu.main]]
    name = "about"
    url = "about"
    weight = 10